### ISSUE TITLE
Building Presentation Fails

### ISSUE THREAD

**Issue by ChrisMissal** [trevordmiller/generator-code-deck#5]
### Problem 
When generating a presentation, an error occurs, preventing me from continuing.

### To Reproduce
Out of the box, a fresh `npm install -g generator-code-deck` gives me this:

```
fs.js:568
  function strWrapper(err, written) {
                ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/generator-code-deck/generators/app/templates/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at module.exports (/usr/local/lib/node_modules/generator-code-deck/node_modules/yeoman-generator/node_modules/isbinaryfile/index.js:14:25)
    at _prepCopy (/usr/local/lib/node_modules/generator-code-deck/node_modules/yeoman-generator/lib/actions/actions.js:46:16)
    at copy (/usr/local/lib/node_modules/generator-code-deck/node_modules/yeoman-generator/lib/actions/actions.js:79:19)
    at yeoman.generators.Base.extend.configuring (/usr/local/lib/node_modules/generator-code-deck/generators/app/index.js:129:8)
    at /usr/local/lib/node_modules/generator-code-deck/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)```
```
### My Thoughts
It appears that commits have been made to fix this, but they haven't been pushed to npm. I believe [this change](8b6ab408a13e965ceeffc0340e691694529e290c) hasn't been published.

**Comment by ChrisMissal** [comment]
The 1.4.0 version fixes this, thanks!

**Comment by trevordmiller** [comment]
@ChrisMissal Sweet! No problem.
